In [1]:
import pandas 
import numpy as np
from tqdm import tqdm
from tqdm import tnrange, tqdm_notebook
from time import sleep
import difflib
import scipy
import operator
import difflib
from IPython.core.display import display,HTML
try:
    import cPickle as pickle     #it is faster than pickle!
except:
    import pickle
    
import unicodedata
    
 
    
display(HTML("<style>.container { width:100% !important; }</style>"))  # to make the notebook use the entire width of the browser

In [2]:
#for item in sorted(df['First name']):
 #   print item
#for item in df.columns:
 #   print item    
#df[0:3]
#sort= df.sort_values(['Last Name'], ascending=False)
path_linkedin_linux="/home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/"
#path_linkedin_win='C:\\Users\\julietta\\Work\\Dropbox_studies\\Data\\Vinu_University_Sheets\\Improved_3Feb\\'   
path_rest_70univ_linux="/home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/rest_70univ_without_linkedin_info/"

list_university_files=['1.Harvard_University_removed_duplicates.xlsx','2.University_of_Chicago_removed_duplicates.xlsx',\
'3.Stanford_University_removed_duplicates.xlsx','4.University_of_California_Berkeley_removed_duplicates.xlsx', \
'5.Massachusetts_Institute_of_Technology_removed_duplicates.xlsx','6.Johns_Hopkins_University_removed_duplicates.xlsx',\
'7.University_of_Michigan_removed_duplicates.xlsx','8.Michigan_State_University_removed_duplicates.xlsx',\
'9.Yale_University_removed_duplicates.xlsx','10.University_of_California_San_Diego_removed_duplicates.xlsx',\
'11.University_of_California_Los_Angeles_removed_duplicates.xlsx','12.Columbia_University_removed_duplicates.xlsx',\
'13.Duke_University_removed_duplicates.xlsx','14.University_of_Washington_removed_duplicates.xlsx',\
'15.Princeton_University_removed_duplicates.xlsx','16.Carnegie_Mellon_University_removed_duplicates.xlsx',\
'17.University_of_Rochester_removed_duplicates.xlsx','18.Arizona_State_University_removed_duplicates.xlsx',\
'19.Pennsylvania_State_University_removed_duplicates.xlsx','20.Cornell_University_removed_duplicates.xlsx', \
'21.New_York_University_removed_duplicates.xlsx','22.University_of_Minnesota_removed_duplicates.xlsx',\
'23.Temple_University_removed_duplicates.xlsx','24.Ohio_State_University_removed_duplicates.xlsx',\
'25.University_of_Illinois_Urbana_Champaign_removed_duplicates.xlsx','26.University_of_North_Carolina_Chapel_Hill_removed_duplicates.xlsx',\
'27.Boston_University_removed_duplicates.xlsx','28.Georgia_Institute_of_Technology_removed_duplicates.xlsx',\
'29.University_of_Southern_California_removed_duplicates.xlsx','30.Northwestern_University_removed_duplicates.xlsx']




list_70extra_univ=['17.Washington_University_Saint_Louis_removed_duplicates.xlsx','70.Rensselaer_Polytechnic_Institute_removed_duplicates.xlsx',\
'31.University_of_California_San_Francisco_removed_duplicates.xlsx','71.North_Carolina_State_University_removed_duplicates.xlsx',\
'32.University_of_California_Irvine_removed_duplicates.xlsx','72.University_of_Virginia_removed_duplicates.xlsx',\
'33.University_of_Maryland_removed_duplicates.xlsx','73.Case_Western_Reserve_University_removed_duplicates.xlsx',\
'34.University_of_California_Santa_Barbara_removed_duplicates.xlsx','74.University_of_Iowa_removed_duplicates.xlsx',\
'36.The_University_of_Texas_at_Austin_removed_duplicates.xlsx','75.University_of_Colorado_removed_duplicates.xlsx',\
'37.University_of_Wisconsin_Madison_removed_duplicates.xlsx','76.Colorado_State_University_removed_duplicates.xlsx',\
'38.University_of_Massachusetts_Boston_removed_duplicates.xlsx','77.City_University_of_New_York_removed_duplicates.xlsx',\
'39.University_of_Pittsburgh_removed_duplicates.xlsx','78.University_of_Connecticut_removed_duplicates.xlsx',\
'40.University_of_Pennsylvania_removed_duplicates.xlsx','79.Virginia_Polytechnic_Institute_and_State_University_removed_duplicates.xlsx',\
'41.Vanderbilt_University_removed_duplicates.xlsx','80.University_of_Arizona_removed_duplicates.xlsx',\
'42.University_of_California_Davis_removed_duplicates.xlsx','81.University_of_Cincinnati_removed_duplicates.xlsx',\
'43.California_Institute_of_Technology_removed_duplicates.xlsx','82.University_of_New_Mexico_removed_duplicates.xlsx',\
'44.University_of_Florida_removed_duplicates.xlsx','83.University_of_Miami_removed_duplicates.xlsx',\
'45.Rice_University_removed_duplicates.xlsx','84.Yeshiva_University_removed_duplicates.xlsx',\
'46.Northeastern_University_removed_duplicates.xlsx','85.University_of_South_Florida_removed_duplicates.xlsx',\
'47.Rutgers_The_State_University_of_New_Jersey_removed_duplicates.xlsx','86.University_of_Arkansas_removed_duplicates.xlsx',\
'48.Emory_University_removed_duplicates.xlsx','87.Florida_State_University_removed_duplicates.xlsx',\
'49.Tufts_University_removed_duplicates.xlsx','88.University_of_New_Hampshire_removed_duplicates.xlsx',\
'50.Texas_AM_University_removed_duplicates.xlsx','89.University_of_Hawaii_removed_duplicates.xlsx',\
'51.Indiana_University_Bloomington_removed_duplicates.xlsx','90.University_of_Central_Florida_removed_duplicates.xlsx',\
'52.University_of_Notre_Dame_removed_duplicates.xlsx','91.University_of_Nebraska_removed_duplicates.xlsx',\
'53.Brown_University_removed_duplicates.xlsx','92.University_of_Alabama_removed_duplicates.xlsx',\
'54.MD_Anderson_Cancer_Center_University_of_Texas_removed_duplicates.xlsx','93.University_of_Delaware_removed_duplicates.xlsx',\
'55.University_of_Vermont_removed_duplicates.xlsx','94.Drexel_University_removed_duplicates.xlsx',\
'56.Iowa_State_University_removed_duplicates.xlsx','95.Syracuse_University_removed_duplicates.xlsx',\
'58.Stony_Brook_University_removed_duplicates.xlsx','97.Oregon_Health_Science_University_removed_duplicates.xlsx',\
'60.Dartmouth_College_removed_duplicates.xlsx','98.University_at_Buffalo_removed_duplicates.xlsx',\
'61.University_of_California_Santa_Cruz_removed_duplicates.xlsx','99.George_Washington_University_removed_duplicates.xlsx',\
'62.University_of_Utah_removed_duplicates.xlsx','Georgetown_University_removed_duplicates.xlsx',\
'63.Purdue_University_removed_duplicates.xlsx','Oregon_State_University_removed_duplicates.xlsx',\
'64.University_of_California_Riverside_removed_duplicates.xlsx','Rockefeller_University_removed_duplicates.xlsx',\
'65.Baylor_College_of_Medicine_removed_duplicates.xlsx','The_University_of_Tennessee_Knoxville_removed_duplicates.xlsx',\
'68.University_of_Georgia_removed_duplicates.xlsx','University_of_Houston_removed_duplicates.xlsx',\
'69.University_of_Illinois_Chicago_removed_duplicates.xlsx','University_of_Kansas_removed_duplicates.xlsx']
    
    
    

#list_university_files=["10.University_of_California_San_Diego_removed_duplicates.xlsx","24.Ohio_State_University_removed_duplicates.xlsx","11.University_of_California_Los_Angeles_removed_duplicates.xlsx","25.University_of_Illinois_Urbana_Champaign_removed_duplicates.xlsx","12.Columbia_University_removed_duplicates.xlsx","26.University_of_North_Carolina_Chapel_Hill_removed_duplicates.xlsx","13.Duke_University_removed_duplicates.xlsx","14.University_of_Washington_removed_duplicates.xlsx","27.Boston_University_removed_duplicates.xlsx","15.Princeton_University_removed_duplicates.xlsx","28.Georgia_Institute_of_Technology_removed_duplicates.xlsx","16.Carnegie_Mellon_University_removed_duplicates.xlsx","2.University_of_Chicago_removed_duplicates.xlsx","17.University_of_Rochester_removed_duplicates.xlsx","30.Northwestern_University_removed_duplicates.xlsx","18.Arizona_State_University_removed_duplicates.xlsx","3.Stanford_University_removed_duplicates.xlsx","19.Pennsylvania_State_University_removed_duplicates.xlsx","4.University_of_California_Berkeley_removed_duplicates.xlsx","1.Harvard_University_removed_duplicates.xlsx","5.Massachusetts_Institute_of_Technology_removed_duplicates.xlsx","20.Cornell_University_removed_duplicates.xlsx","6.Johns_Hopkins_University_removed_duplicates.xlsx","21.New_York_University_removed_duplicates.xlsx","7.University_of_Michigan_removed_duplicates.xlsx","22.University_of_Minnesota_removed_duplicates.xlsx","8.Michigan_State_University_removed_duplicates.xlsx","23.Temple_University_removed_duplicates.xlsx","9.Yale_University_removed_duplicates.xlsx"]    

# list_university_files=['3.Stanford_University_removed_duplicates.xlsx']
### OJO!!! Give all files the same headers as 5.MIT has, so i can read them all automatically


#for item in df.columns:
 #   print item    

list_all_uni_files=[]
for item in list_university_files:
    item=path_linkedin_linux+item   
    list_all_uni_files.append(item)
# print ("number of files read:",len(list_university_files))



for item in list_70extra_univ:
    item=path_rest_70univ_linux+item
    list_all_uni_files.append(item)

In [8]:
len(list_all_uni_files)

100

In [3]:
tot_num_unique_names=0
tot_cont_linkedin=0
tot_cont_cv=0

tot_num_emails=0
tot_num_current_pos=0
tot_num_prev_pos=0
tot_num_ed=0
tot_all_info =0  
   
tot_some_info=0    
list_df=[]



cont_files=0
dict_filenames_fract_info={}

list_headers=["firstname","lastname","Current_Title","Email","University","School/college","Department(s)","Url","CV_Url","Linkedin_Url","Starting_Year_Current_Position","Institution_Bachelors_Degree","Field_Bachelors_Degree","Years_Bachelors_Degree","Institution_Masters","Field_Masters","Years_Masters","Institution_Phd","Field_Phd","Years_Phd","Previous_Title_0","Previous_Institution_0","Years_0","Department_0","Previous_Title_1","Previous_Institution_1","Years_1","Department_1","Previous_Title_2","Previous_Institution_2","Years_2","Department_2","Previous_Title_3","Previous_Institution_3","Years_3","Department_3","Previous_Title_4","Previous_Institution_4","Years_4","Department_4","Previous_Title_5","Previous_Institution_5","Years_5","Department_5","Previous_Title_6","Previous_Institution_6","Years_6","Department_6","Previous_Title_7","Previous_Institution_7","Years_7","Department_7","Previous_Title_8","Previous_Institution_8","Years_8","Department_8","Previous_Title_9","Previous_Institution_9","Years_9","Department_9","Previous_Title_10","Previous_Institution_10","Years_10","Department_10","Previous_Title_11","Previous_Institution_11","Years_11","Department_11","Previous_Title_12","Previous_Institution_12","Years_12","Department_12","Previous_Title_13","Previous_Institution_13","Years_13","Department_13","Previous_Title_14","Previous_Institution_14","Years_14","Department_14","Previous_Title_15","Previous_Institution_15","Years_15","Department_15","Previous_Title_16","Previous_Institution_16","Years_16","Department_16","Previous_Title_17","Previous_Institution_17","Years_17","Department_17","Previous_Title_18","Previous_Institution_18","Years_18","Department_18","Previous_Title_19","Previous_Institution_19","Years_19","Department_19","Previous_Title_20","Previous_Institution_20","Years_20","Department_20","Previous_Title_21","Previous_Institution_21","Years_21","Department_21","Previous_Title_22","Previous_Institution_22","Years_22","Department_22","Previous_Title_23","Previous_Institution_23","Years_23","Department_23","Previous_Title_24","Previous_Institution_24","Years_24","Department_24","Previous_Title_25","Previous_Institution_25","Years_25","Department_25","Previous_Title_26","Previous_Institution_26","Years_26","Department_26","Previous_Title_27","Previous_Institution_27","Years_27","Department_27","Previous_Title_28","Previous_Institution_28","Years_28","Department_28","Previous_Title_29","Previous_Institution_29","Years_29","Department_29"]
   

for filename in list_all_uni_files:
    cont_files +=1
    print "\n\n",cont_files, "  ",filename
    
   
    df = pandas.read_excel(open(filename,'rb'), na_values=["nan","NaN","--","..","..."," "])
    df.columns = [col.strip() for col in df.columns]  # i remove spaces in field names
    
    
    

#            firstname	lastname	Current_Title	Email	University	School/college	Department(s)	Url	CV_Url
#         Linkedin_Url
#         Starting_Year_Current_Position	Institution_Bachelors_Degree	Field_Bachelors_Degree	
#         Years_Bachelors_Degree	Institution_Masters	Field_Masters	Years_Masters	Institution_Phd	Field_Phd	
#         Years_Phd	Previous Title_0	Previous Institution_0	Years_0	Department_0	Previous Title_1	
#         Previous Institution_1	Years_1	Department_1	Previous Title_2	Previous Institution_2	Years_2	Department_2	Previous Title_3	Previous Institution_3	Years_3	Department_3	Previous Title_4	Previous Institution_4	Years_4	Department_4	Previous Title_5	Previous Institution_5	Years_5	Department_5	Previous Title_6	Previous Institution_6	Years_6	Department_6	Previous Title_7	Previous Institution_7	Years_7	Department_7	Previous Title_8	Previous Institution_8	Years_8	Department_8	Previous Title_9	Previous Institution_9	Years_9	Department_9	Previous Title_10	Previous Institution_10	Years_10	Department_10	Previous Title_11	Previous Institution_11	Years_11	Department_11	Previous Title_12	Previous Institution_12	Years_12	Department_12	Previous Title_13	Previous Institution_13	Years_13	Department_13	Previous Title_14	Previous Institution_14	Years_14	Department_14	Previous Title_15	Previous Institution_15	Years_15	Department_15	Previous Title_16	Previous Institution_16	Years_16	Department_16	Previous Title_17	Previous Institution_17	Years_17	Department_17	Previous Title_18	Previous Institution_18	Years_18	Department_18	Previous Title_19	Previous Institution_19	Years_19	Department_19	Previous Title_20	Previous Institution_20	Years_20	Department_20	Previous Title_21	Previous Institution_21	Years_21	Department_21	Previous Title_22	Previous Institution_22	Years_22	Department_22	Previous Title_23	Previous Institution_23	Years_23	Department_23	Previous Title_24	Previous Institution_24	Years_24	Department_24	Previous Title_25	Previous Institution_25	Years_25	Department_25	Previous Title_26	Previous Institution_26	Years_26	Department_26	Previous Title_27	Previous Institution_27	Years_27	Department_27	Previous Title_28	Previous Institution_28	Years_28	Department_28	Previous Title_29	Previous Institution_29	Years_29	Department_29
              

    
    
    
    
    
    
    test = df.copy()
    

    test = test[[c for c in test.columns if not c.startswith('Unnamed')]]  # remove some extra columns
    
    indice=len(test.columns)
    test.columns = list_headers[:indice]
    
    #print len(test.columns), len(list_headers)   #160 140
    indice=len(test.columns)
    test.columns = list_headers[:indice]
    
    
   
    list_df.append(test)
   

    
    
    
    master_dict={}    
    list_for_dropping=[]
    cont =0
    cont_linkedin=0
    cont_cv=0
    num_unique_names=0    
     
    
    num_emails=0
    num_current_pos=0
    num_prev_pos=0
    num_ed=0    
    all_info =0          
    some_info =0                
        
   
    
    ##### lambda x: x if pd.isnull(x) else x.lower()
    
#     test['firstname'] = test.apply(lambda row: row.firstname .replace("."," ").replace("-","").lower(), axis=1)    
   
    #test['lastname'] = test.apply(lambda row: row.lastname .replace("."," ").replace("-","").lower(), axis=1)
    
     
    
    # reformating the names
   
    test['lastname'] =  test['lastname'].str.replace("."," ").str.replace("-","").str.strip().str.lower()
    test['firstname'] =  test['firstname'].str.replace("."," ").str.replace("-","").str.strip().str.lower()
    
    
    for index, row in test.iterrows():
       cont +=1
           # print cont
                 
        
       if   pandas.isnull(row['firstname']) == False  or   pandas.isnull(row['lastname']) == False:
        
         
        try:  # to solve some name issues like:first: Marco   last: nan  (i cant concatenate that)
            row['firstname'] + " " 
            first=row['firstname']
        except TypeError:
            first=""
            
        try:    
            row['lastname'] + " "      
            last=row['lastname']
        except TypeError:
            last =""
            
        #print  first,last,row['University']   
        try:
            name= first + " " + last + " " +row['University']
        except :
                print  first,last,row['University']   
        
        
        flag_all_info=0
        
        if name not in master_dict:   # i ignore any duplicates!
                master_dict [name] ={}
                tot_num_unique_names +=1
                num_unique_names +=1  # in the file
               

                
                linkedin= row['Linkedin_Url']
                cv_url=row['CV_Url'] 

    
                if pandas.isnull(row['Linkedin_Url']) == False and "NO_LinkedIn profile" not in linkedin:                  
                    cont_linkedin  +=1   
                    tot_cont_linkedin  +=1   
                elif pandas.isnull(row['CV_Url']) == False:    ### how to check if an element is nan                                      
                    cont_cv +=1
                    tot_cont_cv +=1

                
                       
                   
                
                
    
                if   row['Email']  != '..'  and   row['Email']  != '...'  and   row['Email']  != '--'  and   row['Email']  != '':  
                    flag_all_info  +=1
                
                
                if   pandas.isnull(row['Current_Title']) == False:
                    num_current_pos +=1 
                    tot_num_current_pos +=1 
                    
                    flag_all_info  +=1
                    
                    
                    
                    #    if   pandas.isnull(row['Starting_Year_Current_Position']) == False:
                    #  flag_some_info = 1 
                  
                
#                 if   pandas.isnull(row['Institution_Phd']) == False  or   pandas.isnull(row['Field_Phd']) == False\
#                     or pandas.isnull(row['Years_Phd']) == False:
#                         num_ed +=1
#                         tot_num_ed +=1
                
                if   pandas.isnull(row['Previous_Title_0']) == False or  pandas.isnull(row['Previous_Institution_0']) == False\
                    or pandas.isnull(row['Years_0']) == False  or pandas.isnull(row['Department_0']) == False:
                    num_prev_pos +=1
                    tot_num_prev_pos +=1
                
                    flag_all_info  +=1
                        


                if pandas.isnull(row['Institution_Bachelors_Degree']) == False or \
    pandas.isnull(row['Field_Bachelors_Degree']) == False or pandas.isnull(row['Years_Bachelors_Degree']) == False or\
    pandas.isnull(row['Institution_Masters'] ) == False or pandas.isnull(row['Field_Masters']) == False or\
    pandas.isnull(row['Years_Masters']) == False or  pandas.isnull(row['Institution_Phd']) == False or\
    pandas.isnull(row['Field_Phd']) == False or pandas.isnull(row['Years_Phd']) == False:
        
                    num_ed +=1
                    tot_num_ed +=1        
                    flag_all_info  +=1
                 
                if flag_all_info == 4:
                     all_info +=1                
                     tot_all_info +=1
                    
                    
                if flag_all_info >= 3:    
                 some_info +=1   
                 tot_some_info +=1
                
        else:
                list_for_dropping.append(index) 
                
      
     
   
    num_emails = num_unique_names-test['Email'].isnull().sum()
    tot_num_emails += num_emails
   
            
            
    N=float(len(test.values))
    print "# names before dropping",N, "  after:",  num_unique_names," with:" 
    print "# rows to be dropped: ", len(list_for_dropping)  , "  out of:",cont 
    print "    linkedIn profile:", cont_linkedin, float(cont_linkedin)/num_unique_names
    print "    cv url:", cont_cv, float(cont_cv)/num_unique_names
    print "       linkedIn   OR   cv url:", cont_cv+cont_linkedin, float(cont_cv+cont_linkedin)/num_unique_names 
   
    print "    emails:",num_emails,num_emails/ float(num_unique_names)
    print "    num_current_pos:",num_current_pos,num_current_pos/ float(num_unique_names)
    print "    num_prev_pos:",num_prev_pos, num_prev_pos/float(num_unique_names)
    print "    num_ed:",num_ed, num_ed/float(num_unique_names)
    print "      with all info in the 4 fields:", all_info, float(all_info)/float(num_unique_names)
    print "      with some info in (3 out of 4) fields:", some_info, float(some_info)/float(num_unique_names)
    
    print "-----# emails so far:",tot_num_emails,tot_num_emails/float(tot_num_unique_names)
    print "tot fract. all info (so far):", float(tot_all_info) /tot_num_unique_names
    print "# unique names(so far):", tot_num_unique_names,"\n\n\n"
          
   
    
    
    
    dict_filenames_fract_info[filename]=(num_unique_names, float(cont_linkedin)/num_unique_names, \
                        cont_linkedin, float(cont_cv)/num_unique_names, \
                        cont_cv, float(all_info)/num_unique_names, \
                        all_info, float(some_info)/float(num_unique_names), some_info,\
                        num_emails, num_emails/ float(num_unique_names),\
                        num_current_pos, num_current_pos/ float(num_unique_names), \
                        num_prev_pos, num_prev_pos/float(num_unique_names), num_ed,\
                        num_ed/float(num_unique_names) )
    

     
print "\ntot num. unique names:",tot_num_unique_names, "with:"
print "   linkedin:",tot_cont_linkedin,float(tot_cont_linkedin)/tot_num_unique_names
print "   cv url:",tot_cont_cv,float(tot_cont_cv)/tot_num_unique_names   
print "      linkedIn or cv url:", tot_cont_cv+tot_cont_linkedin, float(tot_cont_cv+tot_cont_linkedin)/tot_num_unique_names
  
print "   emails:",tot_num_emails,tot_num_emails/float(tot_num_unique_names)
print "   num_current_pos:",tot_num_current_pos,tot_num_current_pos/ float(tot_num_unique_names)
print "   num_prev_pos:",tot_num_prev_pos, tot_num_prev_pos/float(tot_num_unique_names)
print "   num_ed:",tot_num_ed, tot_num_ed/float(tot_num_unique_names)
print "      with all info in the 4 fields:", float(tot_all_info) /tot_num_unique_names, tot_all_info
print "      with all some in (3 out of 4) fields:", float(tot_some_info) /tot_num_unique_names, tot_some_info,"\n\n\n"

1    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/1.Harvard_University_removed_duplicates.xlsx
# names before dropping 2173.0   after: 2091  with:
# rows to be dropped:  82   out of: 2173
    linkedIn profile: 922 0.44093735055
    cv url: 744 0.35581061693
       linkedIn   OR   cv url: 1666 0.79674796748
    emails: 2073 0.991391678623
    num_current_pos: 2025 0.96843615495
    num_prev_pos: 920 0.439980870397
    num_ed: 1345 0.643232902917
      with all info in the 4 fields: 719 0.343854615017
      with some info in (3 out of 4) fields: 1518 0.725968436155
-----# emails so far: 2073 0.991391678623
tot fract. all info (so far): 0.343854615017
# unique names(so far): 2091





2    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/2.University_of_Chicago_removed_duplicates.xlsx
# names before dropping 2013.0   after: 2011  with:
# rows to be dropped:  2   out of: 2013
    linkedIn profile: 879 0.437095972153
    cv url: 785 0.39035305818
       linkedIn   OR   cv url: 1664 0.827449030333
    emails: 1958 0.97364495276
    num_current_pos: 2011 1.0
    num_prev_pos: 589 0.292889109896
    num_ed: 1281 0.636996519145
      with all info in the 4 fields: 550 0.273495773247
      with some info in (3 out of 4) fields: 1320 0.656389855793
-----# emails so far: 4031 0.982691370063
tot fract. all info (so far): 0.309361287177
# unique names(so far): 4102





3    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/3.Stanford_University_removed_duplicates.xlsx
# names before dropping 2039.0   after: 2016  with:
# rows to be dropped:  23   out of: 2039
    linkedIn profile: 1008 0.5
    cv url: 132 0.0654761904762
       linkedIn   OR   cv url: 1140 0.565476190476
    emails: 1962 0.973214285714
    num_current_pos: 1981 0.982638888889
    num_prev_pos: 614 0.304563492063
    num_ed: 792 0.392857142857
      with all info in the 4 fields: 567 0.28125
      with some info in (3 out of 4) fields: 827 0.410218253968
-----# emails so far: 5993 0.979568486433
tot fract. all info (so far): 0.300098071265
# unique names(so far): 6118





4    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/4.University_of_California_Berkeley_removed_duplicates.xlsx
# names before dropping 3123.0   after: 3119  with:
# rows to be dropped:  4   out of: 3123
    linkedIn profile: 1456 0.466816287272
    cv url: 1218 0.390509778775
       linkedIn   OR   cv url: 2674 0.857326066047
    emails: 3050 0.977877524848
    num_current_pos: 2970 0.952228278294
    num_prev_pos: 1212 0.388586085284
    num_ed: 2105 0.674895799936
      with all info in the 4 fields: 1075 0.344661750561
      with some info in (3 out of 4) fields: 2135 0.684514267393
-----# emails so far: 9043 0.978997510014
tot fract. all info (so far): 0.315145610047
# unique names(so far): 9237





5    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/5.Massachusetts_Institute_of_Technology_removed_duplicates.xlsx
# names before dropping 1521.0   after: 1509  with:
# rows to be dropped:  12   out of: 1521
    linkedIn profile: 751 0.497680583168
    cv url: 544 0.360503644798
       linkedIn   OR   cv url: 1295 0.858184227966
    emails: 1503 0.996023856859
    num_current_pos: 1506 0.998011928429
    num_prev_pos: 443 0.293571901922
    num_ed: 1005 0.666003976143
      with all info in the 4 fields: 402 0.266401590457
      with some info in (3 out of 4) fields: 1045 0.692511597084
-----# emails so far: 10546 0.981388423599
tot fract. all info (so far): 0.308300763075
# unique names(so far): 10746





6    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/6.Johns_Hopkins_University_removed_duplicates.xlsx
# names before dropping 3671.0   after: 3657  with:
# rows to be dropped:  14   out of: 3671
    linkedIn profile: 1183 0.323489198797
    cv url: 1828 0.499863275909
       linkedIn   OR   cv url: 3011 0.823352474706
    emails: 2471 0.675690456658
    num_current_pos: 3652 0.998632759092
    num_prev_pos: 1457 0.398414000547
    num_ed: 2409 0.658736669401
      with all info in the 4 fields: 1277 0.349193327864
      with some info in (3 out of 4) fields: 2586 0.707136997539
-----# emails so far: 13017 0.903770047907
tot fract. all info (so far): 0.318683607582
# unique names(so far): 14403





7    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/7.University_of_Michigan_removed_duplicates.xlsx
# names before dropping 2457.0   after: 2457  with:
# rows to be dropped:  0   out of: 2457
    linkedIn profile: 1220 0.49654049654
    cv url: 1168 0.475376475376
       linkedIn   OR   cv url: 2388 0.971916971917
    emails: 2396 0.975172975173
    num_current_pos: 2428 0.988196988197
    num_prev_pos: 2276 0.926332926333
    num_ed: 1678 0.682946682947
      with all info in the 4 fields: 1603 0.652421652422
      with some info in (3 out of 4) fields: 2322 0.945054945055
-----# emails so far: 15413 0.914175563464
tot fract. all info (so far): 0.367319098458
# unique names(so far): 16860





8    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/8.Michigan_State_University_removed_duplicates.xlsx
# names before dropping 2159.0   after: 2159  with:
# rows to be dropped:  0   out of: 2159
    linkedIn profile: 1271 0.588698471515
    cv url: 310 0.143584993052
       linkedIn   OR   cv url: 1581 0.732283464567
    emails: 2006 0.929133858268
    num_current_pos: 2146 0.99397869384
    num_prev_pos: 883 0.408985641501
    num_ed: 1355 0.627605372858
      with all info in the 4 fields: 839 0.388605836035
      with some info in (3 out of 4) fields: 1393 0.645206113942
-----# emails so far: 17419 0.915873600084
tot fract. all info (so far): 0.36973552763
# unique names(so far): 19019





9    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/9.Yale_University_removed_duplicates.xlsx
# names before dropping 4143.0   after: 4108  with:
# rows to be dropped:  35   out of: 4143
    linkedIn profile: 1418 0.345180136319
    cv url: 1544 0.375851996105
       linkedIn   OR   cv url: 2962 0.721032132425
    emails: 3672 0.893865628043
    num_current_pos: 3785 0.921372930867
    num_prev_pos: 2563 0.623904576436
    num_ed: 2674 0.650925024343
      with all info in the 4 fields: 2097 0.510467380721
      with some info in (3 out of 4) fields: 2952 0.718597857838
-----# emails so far: 21091 0.911964370649
tot fract. all info (so far): 0.39473342846
# unique names(so far): 23127





10    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/10.University_of_California_San_Diego_removed_duplicates.xlsx
# names before dropping 2643.0   after: 2517  with:
# rows to be dropped:  126   out of: 2643
    linkedIn profile: 1197 0.475566150179
    cv url: 792 0.314660309893
       linkedIn   OR   cv url: 1989 0.790226460072
    emails: 2476 0.983710766786
    num_current_pos: 2517 1.0
    num_prev_pos: 887 0.352403655145
    num_ed: 1322 0.525228446563
      with all info in the 4 fields: 785 0.311879221295
      with some info in (3 out of 4) fields: 1424 0.565752880413
-----# emails so far: 23567 0.919006395258
tot fract. all info (so far): 0.386601154266
# unique names(so far): 25644





11    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/11.University_of_California_Los_Angeles_removed_duplicates.xlsx
# names before dropping 3332.0   after: 3330  with:
# rows to be dropped:  2   out of: 3332
    linkedIn profile: 1439 0.432132132132
    cv url: 500 0.15015015015
       linkedIn   OR   cv url: 1939 0.582282282282
    emails: 3223 0.967867867868
    num_current_pos: 3329 0.9996996997
    num_prev_pos: 1000 0.3003003003
    num_ed: 1347 0.404504504505
      with all info in the 4 fields: 675 0.202702702703
      with some info in (3 out of 4) fields: 1672 0.502102102102
-----# emails so far: 26790 0.924622074964
tot fract. all info (so far): 0.365465589839
# unique names(so far): 28974





12    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/12.Columbia_University_removed_duplicates.xlsx
# names before dropping 3281.0   after: 3278  with:
# rows to be dropped:  3   out of: 3281
    linkedIn profile: 1534 0.467968273337
    cv url: 1203 0.366992068334
       linkedIn   OR   cv url: 2737 0.834960341672
    emails: 2975 0.907565588774
    num_current_pos: 3247 0.990543014033
    num_prev_pos: 1015 0.309640024405
    num_ed: 731 0.223001830384
      with all info in the 4 fields: 617 0.188224527151
      with some info in (3 out of 4) fields: 1117 0.340756558877
-----# emails so far: 29765 0.922888503039
tot fract. all info (so far): 0.347451320848
# unique names(so far): 32252





13    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/13.Duke_University_removed_duplicates.xlsx
# names before dropping 1713.0   after: 1653  with:
# rows to be dropped:  60   out of: 1713
    linkedIn profile: 821 0.496672716273
    cv url: 748 0.452510586812
       linkedIn   OR   cv url: 1569 0.949183303085
    emails: 1627 0.984271022384
    num_current_pos: 1652 0.999395039322
    num_prev_pos: 760 0.459770114943
    num_ed: 1225 0.741076830006
      with all info in the 4 fields: 598 0.361766485178
      with some info in (3 out of 4) fields: 1386 0.838475499093
-----# emails so far: 31392 0.925881138475
tot fract. all info (so far): 0.348149240525
# unique names(so far): 33905





14    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/14.University_of_Washington_removed_duplicates.xlsx
# names before dropping 4696.0   after: 4694  with:
# rows to be dropped:  2   out of: 4696
    linkedIn profile: 2244 0.478057094163
    cv url: 794 0.169152109075
       linkedIn   OR   cv url: 3038 0.647209203238
    emails: 4225 0.900085215168
    num_current_pos: 4694 1.0
    num_prev_pos: 2210 0.470813804857
    num_ed: 2406 0.512569237324
      with all info in the 4 fields: 1916 0.408180656157
      with some info in (3 out of 4) fields: 2700 0.575202386025
-----# emails so far: 35617 0.922744112542
tot fract. all info (so far): 0.355449623047
# unique names(so far): 38599





15    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/15.Princeton_University_removed_duplicates.xlsx
# names before dropping 1189.0   after: 1106  with:
# rows to be dropped:  83   out of: 1189
    linkedIn profile: 443 0.400542495479
    cv url: 0 0.0
       linkedIn   OR   cv url: 443 0.400542495479
    emails: 1000 0.904159132007
    num_current_pos: 1062 0.960216998192
    num_prev_pos: 359 0.324593128391
    num_ed: 831 0.751356238698
      with all info in the 4 fields: 311 0.281193490054
      with some info in (3 out of 4) fields: 856 0.773960216998
-----# emails so far: 36617 0.922226419846
tot fract. all info (so far): 0.353381186249
# unique names(so far): 39705





16    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/16.Carnegie_Mellon_University_removed_duplicates.xlsx
# names before dropping 1640.0   after: 1523  with:
# rows to be dropped:  117   out of: 1640
    linkedIn profile: 1028 0.67498358503
    cv url: 222 0.145764937623
       linkedIn   OR   cv url: 1250 0.820748522653
    emails: 1467 0.963230466185
    num_current_pos: 1468 0.963887065003
    num_prev_pos: 1009 0.662508207485
    num_ed: 988 0.648719632305
      with all info in the 4 fields: 795 0.521996060407
      with some info in (3 out of 4) fields: 1154 0.757715036113
-----# emails so far: 38084 0.923741146793
tot fract. all info (so far): 0.359609973804
# unique names(so far): 41228





17    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/17.University_of_Rochester_removed_duplicates.xlsx
# names before dropping 745.0   after: 735  with:
# rows to be dropped:  10   out of: 745
    linkedIn profile: 394 0.536054421769
    cv url: 323 0.439455782313
       linkedIn   OR   cv url: 717 0.975510204082
    emails: 664 0.903401360544
    num_current_pos: 735 1.0
    num_prev_pos: 383 0.521088435374
    num_ed: 653 0.88843537415
      with all info in the 4 fields: 363 0.49387755102
      with some info in (3 out of 4) fields: 673 0.915646258503
-----# emails so far: 38748 0.923384886686
tot fract. all info (so far): 0.361961728189
# unique names(so far): 41963





18    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/18.Arizona_State_University_removed_duplicates.xlsx
# names before dropping 1876.0   after: 1874  with:
# rows to be dropped:  2   out of: 1876
    linkedIn profile: 1231 0.656883671291
    cv url: 475 0.253468516542
       linkedIn   OR   cv url: 1706 0.910352187834
    emails: 1831 0.977054429029
    num_current_pos: 1870 0.997865528282
    num_prev_pos: 947 0.505336179296
    num_ed: 1231 0.656883671291
      with all info in the 4 fields: 891 0.47545357524
      with some info in (3 out of 4) fields: 1285 0.685699039488
-----# emails so far: 40579 0.92567922075
tot fract. all info (so far): 0.366813422451
# unique names(so far): 43837





19    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/19.Pennsylvania_State_University_removed_duplicates.xlsx
# names before dropping 3783.0   after: 3749  with:
# rows to be dropped:  34   out of: 3783
    linkedIn profile: 2263 0.603627634036
    cv url: 971 0.25900240064
       linkedIn   OR   cv url: 3234 0.862630034676
    emails: 3670 0.978927714057
    num_current_pos: 3706 0.98853027474
    num_prev_pos: 2075 0.553480928248
    num_ed: 2558 0.682315284076
      with all info in the 4 fields: 1514 0.403841024273
      with some info in (3 out of 4) fields: 3081 0.821819151774
-----# emails so far: 44249 0.929874332787
tot fract. all info (so far): 0.369730593032
# unique names(so far): 47586





20    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/20.Cornell_University_removed_duplicates.xlsx
# names before dropping 3834.0   after: 3774  with:
# rows to be dropped:  60   out of: 3834
    linkedIn profile: 1865 0.494170641229
    cv url: 458 0.121356650768
       linkedIn   OR   cv url: 2323 0.615527291998
    emails: 3408 0.903020667727
    num_current_pos: 3761 0.996555378908
    num_prev_pos: 1520 0.402755696873
    num_ed: 1632 0.432432432432
      with all info in the 4 fields: 1037 0.274774774775
      with some info in (3 out of 4) fields: 2109 0.558823529412
-----# emails so far: 47657 0.927901090343
tot fract. all info (so far): 0.362753115265
# unique names(so far): 51360





21    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/21.New_York_University_removed_duplicates.xlsx
# names before dropping 1453.0   after: 1453  with:
# rows to be dropped:  0   out of: 1453
    linkedIn profile: 619 0.426015141087
    cv url: 201 0.138334480385
       linkedIn   OR   cv url: 820 0.564349621473
    emails: 1344 0.924982794219
    num_current_pos: 1453 1.0
    num_prev_pos: 511 0.351686166552
    num_ed: 575 0.395732966277
      with all info in the 4 fields: 347 0.238816242257
      with some info in (3 out of 4) fields: 739 0.508602890571
-----# emails so far: 49001 0.927820801697
tot fract. all info (so far): 0.359343343495
# unique names(so far): 52813





22    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/22.University_of_Minnesota_removed_duplicates.xlsx
# names before dropping 2950.0   after: 2948  with:
# rows to be dropped:  2   out of: 2950
    linkedIn profile: 1468 0.497964721845
    cv url: 192 0.0651289009498
       linkedIn   OR   cv url: 1660 0.563093622795
    emails: 2662 0.902985074627
    num_current_pos: 2948 1.0
    num_prev_pos: 1170 0.396879240163
    num_ed: 1270 0.430800542741
      with all info in the 4 fields: 915 0.310379918589
      with some info in (3 out of 4) fields: 1525 0.517299864315
-----# emails so far: 51663 0.926507774251
tot fract. all info (so far): 0.356754721042
# unique names(so far): 55761





23    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/23.Temple_University_removed_duplicates.xlsx
# names before dropping 2238.0   after: 2238  with:
# rows to be dropped:  0   out of: 2238
    linkedIn profile: 1113 0.497319034853
    cv url: 973 0.434763181412
       linkedIn   OR   cv url: 2086 0.932082216265
    emails: 2078 0.928507596068
    num_current_pos: 2236 0.999106344951
    num_prev_pos: 1085 0.484807864164
    num_ed: 1743 0.778820375335
      with all info in the 4 fields: 916 0.409294012511
      with some info in (3 out of 4) fields: 1911 0.853887399464
-----# emails so far: 53741 0.92658494112
tot fract. all info (so far): 0.358782047966
# unique names(so far): 57999





24    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/24.Ohio_State_University_removed_duplicates.xlsx
# names before dropping 4596.0   after: 4586  with:
# rows to be dropped:  10   out of: 4596
    linkedIn profile: 2157 0.470344526821
    cv url: 1119 0.244003488879
       linkedIn   OR   cv url: 3276 0.7143480157
    emails: 4138 0.902311382468
    num_current_pos: 4419 0.963584823375
    num_prev_pos: 2302 0.501962494549
    num_ed: 2429 0.529655473179
      with all info in the 4 fields: 1738 0.378979502835
      with some info in (3 out of 4) fields: 2892 0.630614914959
-----# emails so far: 57879 0.924806263482
tot fract. all info (so far): 0.360262043621
# unique names(so far): 62585





25    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/25.University_of_Illinois_Urbana_Champaign_removed_duplicates.xlsx
# names before dropping 1996.0   after: 1996  with:
# rows to be dropped:  0   out of: 1996
    linkedIn profile: 937 0.469438877756
    cv url: 226 0.113226452906
       linkedIn   OR   cv url: 1163 0.582665330661
    emails: 1803 0.903306613226
    num_current_pos: 1966 0.98496993988
    num_prev_pos: 898 0.449899799599
    num_ed: 904 0.452905811623
      with all info in the 4 fields: 703 0.352204408818
      with some info in (3 out of 4) fields: 1084 0.543086172345
-----# emails so far: 59682 0.924141775445
tot fract. all info (so far): 0.360013006922
# unique names(so far): 64581





26    /home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb_and_more_emails_27Feb/26.University_of_North_Carolina_Chapel_Hill_removed_duplicates.xlsx
# names before dropping 3166.0   after: 3163  with:
# rows to be dropped:  3   out of: 3166
    linkedIn profile: 1615 0.510591210876
    cv url: 1326 0.419222257351
       linkedIn   OR   cv url: 2941 0.929813468226
    emails: 2826 0.893455580145
    num_current_pos: 3161 0.999367688903
    num_prev_pos: 1468 0.464116345242
    num_ed: 2468 0.780271893772

In [4]:

### i concatenate all dataframes (they must have identical column structure!)
df_linkedin = pandas.concat(list_df, ignore_index=True)  ## OJO!! if i dont set up ignore_indx=True, then i will have REPEATED indeces 
# in the final concat. dataframe!!

print "\nsize concatenated df:",df_linkedin.shape

size concatenated df: (225009, 140)

In [23]:


df_linkedin.head(3)

,firstname,lastname,Current_Title,Email,University,School/college,Department(s),Url,CV_Url,Linkedin_Url,...,Years_27,Department_27,Previous_Title_28,Previous_Institution_28,Years_28,Department_28,Previous_Title_29,Previous_Institution_29,Years_29,Department_29
0,nicholas,argyres,Professor of Strategy,argyres@wustl.edu,Washington University in St.Louis,OLIN BUSINESS SCHOOL,Accounting,https://olin.wustl.edu/EN-US/Faculty-Research/...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mariagiovanna,baccara,Associate Professor of Economics,mbaccara@wustl.edu,Washington University in St.Louis,OLIN BUSINESS SCHOOL,Accounting,https://olin.wustl.edu/EN-US/Faculty-Research/...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,markus,baer,Associate Professor of Organizational Behavior,baer@wustl.edu,Washington University in St.Louis,OLIN BUSINESS SCHOOL,Accounting,https://olin.wustl.edu/EN-US/Faculty-Research/...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
def get_middle(string):    
    lista=string.split(" ")
    if len(lista)==3:                
        return lista[1]
    else:
        return ""         ###ISSUE alejandro de la fuente


def get_firstname(string):     
    #print string
    return string.split(" ")[0]


def get_firstname_initial(string):  
    try:
        return string.split(" ")[0][0]
    except:
        print string
        raw_input()



def get_lastname(string):        
    return string.split(" ")[-1]

In [16]:

df_linkedin.rename(columns={'firstname':'dirty_firstname'}, inplace=True) 
df_linkedin.rename(columns={'lastname':'dirty_lastname'}, inplace=True) 



df_linkedin.dirty_firstname = df_linkedin.dirty_firstname.fillna('')  # i convert NaN into empty strings, so i can concatenate them without errors
df_linkedin.dirty_lastname = df_linkedin.dirty_lastname.fillna('')




df_linkedin['full_name'] = df_linkedin['dirty_firstname'] + " "+ df_linkedin['dirty_lastname']  #harold y hwang          ###   rick john w       ###   yanagisako sylvia




df_linkedin['firstname'] = df_linkedin.full_name.apply(get_firstname)
df_linkedin['firstname_initial'] = df_linkedin.full_name.apply(get_firstname_initial)
df_linkedin['lastname'] = df_linkedin.full_name.apply(get_lastname)


df_linkedin['middle'] = df_linkedin.full_name.apply(get_middle)



### rearrange columns' order

list_headers=["dirty_firstname","dirty_lastname","full_name", "firstname","middle","lastname","Current_Title","Email","University","School/college","Department(s)","Url","CV_Url","Linkedin_Url","Starting_Year_Current_Position","Institution_Bachelors_Degree","Field_Bachelors_Degree","Years_Bachelors_Degree","Institution_Masters","Field_Masters","Years_Masters","Institution_Phd","Field_Phd","Years_Phd","Previous_Title_0","Previous_Institution_0","Years_0","Department_0","Previous_Title_1","Previous_Institution_1","Years_1","Department_1","Previous_Title_2","Previous_Institution_2","Years_2","Department_2","Previous_Title_3","Previous_Institution_3","Years_3","Department_3","Previous_Title_4","Previous_Institution_4","Years_4","Department_4","Previous_Title_5","Previous_Institution_5","Years_5","Department_5","Previous_Title_6","Previous_Institution_6","Years_6","Department_6","Previous_Title_7","Previous_Institution_7","Years_7","Department_7","Previous_Title_8","Previous_Institution_8","Years_8","Department_8","Previous_Title_9","Previous_Institution_9","Years_9","Department_9","Previous_Title_10","Previous_Institution_10","Years_10","Department_10","Previous_Title_11","Previous_Institution_11","Years_11","Department_11","Previous_Title_12","Previous_Institution_12","Years_12","Department_12","Previous_Title_13","Previous_Institution_13","Years_13","Department_13","Previous_Title_14","Previous_Institution_14","Years_14","Department_14","Previous_Title_15","Previous_Institution_15","Years_15","Department_15","Previous_Title_16","Previous_Institution_16","Years_16","Department_16","Previous_Title_17","Previous_Institution_17","Years_17","Department_17","Previous_Title_18","Previous_Institution_18","Years_18","Department_18","Previous_Title_19","Previous_Institution_19","Years_19","Department_19","Previous_Title_20","Previous_Institution_20","Years_20","Department_20","Previous_Title_21","Previous_Institution_21","Years_21","Department_21","Previous_Title_22","Previous_Institution_22","Years_22","Department_22","Previous_Title_23","Previous_Institution_23","Years_23","Department_23","Previous_Title_24","Previous_Institution_24","Years_24","Department_24","Previous_Title_25","Previous_Institution_25","Years_25","Department_25","Previous_Title_26","Previous_Institution_26","Years_26","Department_26","Previous_Title_27","Previous_Institution_27","Years_27","Department_27","Previous_Title_28","Previous_Institution_28","Years_28","Department_28","Previous_Title_29","Previous_Institution_29","Years_29","Department_29"]
 
df_linkedin = df_linkedin[list_headers]

 laird

 hao





 scott sallay

 fuchs

In [6]:
df_linkedin.shape

(225009, 140)

In [19]:
len(df_linkedin['Email'].unique())

197435

In [16]:

#new_file_name_linux="/home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/Improved_3Feb/All_linkedIn.csv"


new_file_name=path_linkedin_linux+"All_linkedIn_complete_plus70univ_without_linkedin.tsv"  ## OJO!!! ESTE CREA UNAS 300 LINEAS EXTRAS (POR SALTOS DE CARRO ERRONEOS): USAR MEJOR EL FORMATO XLSX
df_linkedin.to_csv(new_file_name, sep='\t', encoding='utf-8', columns = list_headers)

print "csv done"


df_linkedin.to_pickle(new_file_name.split(".tsv")[0]+".pickle")
  
print "pickle done"


writer = pandas.ExcelWriter(path_linkedin_linux+"All_linkedIn_complete_plus70univ_without_linkedin.xlsx", engine='xlsxwriter',options={'strings_to_urls': False})
# Convert the dataframe to an XlsxWriter Excel object.
df_linkedin.to_excel(writer, sheet_name='Sheet1')
## OJO! hay url muy largas que hacen que el sistema se cuelgue (solucion: no permitirle que las considere url, sino simplemente str)

# Close the Pandas Excel writer and output the Excel file.
writer.save()

print "xlsx done"

csv done
pickle done
xlsx done

In [4]:
#pandas.ExcelWriter?

In [9]:
df_linkedin.head(3)

,firstname,lastname,Current_Title,Email,University,School/college,Department(s),Url,CV_Url,Linkedin_Url,...,Years_27,Department_27,Previous_Title_28,Previous_Institution_28,Years_28,Department_28,Previous_Title_29,Previous_Institution_29,Years_29,Department_29
0,emmanuel,akyeampong,Professor,akyeamp@fas.harvard.edu,Harvard University,NaN,African and African American Studies,http://aaas.fas.harvard.edu/people/taxonomy/te...,NaN,https://www.linkedin.com/in/emmanuel-akyeampon...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ali,asani,Professor,aliasani@fas.harvard.edu,Harvard University,NaN,African and African American Studies,http://aaas.fas.harvard.edu/people/taxonomy/te...,NaN,https://www.linkedin.com/in/ali-asani-a068464,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,robert,bates,Professor,robert.bates.harvard.edu@gmail.com,Harvard University,NaN,African and African American Studies,http://aaas.fas.harvard.edu/people/taxonomy/te...,NaN,https://www.linkedin.com/in/robert-bates-5045064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,robin,bernstein,Professor,rbernst@fas.harvard.edu,Harvard University,NaN,African and African American Studies,http://aaas.fas.harvard.edu/people/taxonomy/te...,NaN,https://www.linkedin.com/in/robin-bernstein-56...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,suzanne,blier,Professor,blier@fas.harvard.edu,Harvard University,NaN,African and African American Studies,http://aaas.fas.harvard.edu/people/taxonomy/te...,NaN,https://www.linkedin.com/in/suzanne-blier-1a41017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_linkedin.shape

(225009, 144)

In [19]:
len(df_linkedin['full_name'].unique())

209116

In [47]:

print "Ranking,University file,Num unique faculty names,fraction unique faculty names with linkedin,Num unique faculty names with linkedin,fraction unique faculty names with cv,Num unique faculty names with cv,fraction unique faculty names with all info,Num unique faculty names with all info,fraction unique faculty names with some info,Num unique faculty names with some info,Num emails,frac emails,Num current pos,fract current pos,Num prev pos,fract prev pos,Num ed,fract ed"



sorted_x = sorted(dict_filenames_fract_info.items(), key=operator.itemgetter(1))

for item in dict_filenames_fract_info:
    print item.replace(".",",").replace("_removed_duplicates","").replace("xlsx","").replace("_"," "), dict_filenames_fract_info[item][0],",",dict_filenames_fract_info[item][1],",",\
    dict_filenames_fract_info[item][2],",",dict_filenames_fract_info[item][3],",",\
    dict_filenames_fract_info[item][4],",",dict_filenames_fract_info[item][5],",",\
    dict_filenames_fract_info[item][6],",",\
    dict_filenames_fract_info[item][7],",",dict_filenames_fract_info[item][8],",",\
    dict_filenames_fract_info[item][9],",",dict_filenames_fract_info[item][10],",",\
    dict_filenames_fract_info[item][11],",",dict_filenames_fract_info[item][12],",",\
    dict_filenames_fract_info[item][13],",",dict_filenames_fract_info[item][14],",",\
    dict_filenames_fract_info[item][15],",",dict_filenames_fract_info[item][16]

Ranking,University file,Num unique faculty names,fraction unique faculty names with linkedin,Num unique faculty names with linkedin,fraction unique faculty names with cv,Num unique faculty names with cv,fraction unique faculty names with all info,Num unique faculty names with all info,fraction unique faculty names with some info,Num unique faculty names with some info,Num emails,frac emails,Num current pos,fract current pos,Num prev pos,fract prev pos,Num ed,fract ed
23,Temple University, 2238 , 0.497319034853 , 1113 , 0.434763181412 , 973 , 0.409294012511 , 916 , 0.853887399464 , 1911 , 2078 , 0.928507596068 , 2236 , 0.999106344951 , 1085 , 0.484807864164 , 1743 , 0.778820375335
20,Cornell University, 3774 , 0.494170641229 , 1865 , 0.121356650768 , 458 , 0.274774774775 , 1037 , 0.558823529412 , 2109 , 3408 , 0.903020667727 , 3761 , 0.996555378908 , 1520 , 0.402755696873 , 1632 , 0.432432432432
30,Northwestern University, 5459 , 0.468950357208 , 2560 , 0.0974537461073 , 532 , 0.36087195457 , 1970 , 0.544788422788 , 2974 , 5325 , 0.97545337974 , 5456 , 0.9994504488 , 2325 , 0.425902179886 , 2621 , 0.480124564939
18,Arizona State University, 1874 , 0.656883671291 , 1231 , 0.253468516542 , 475 , 0.47545357524 , 891 , 0.685699039488 , 1285 , 1831 , 0.977054429029 , 1870 , 0.997865528282 , 947 , 0.505336179296 , 1231 , 0.656883671291
11,University of California Los Angeles, 3330 , 0.432132132132 , 1439 , 0.15015015015 , 500 , 0.202702702703 , 675 , 0.502102102102 , 1672 , 3223 , 0.967867867868 , 3329 , 0.9996996997 , 1000 , 0.3003003003 , 1347 , 0.404504504505
9,Yale University, 4108 , 0.345180136319 , 1418 , 0.375851996105 , 1544 , 0.510467380721 , 2097 , 0.718597857838 , 2952 , 3672 , 0.893865628043 , 3785 , 0.921372930867 , 2563 , 0.623904576436 , 2674 , 0.650925024343
3,Stanford University, 2016 , 0.5 , 1008 , 0.0654761904762 , 132 , 0.28125 , 567 , 0.410218253968 , 827 , 1962 , 0.973214285714 , 1981 , 0.982638888889 , 614 , 0.304563492063 , 792 , 0.392857142857
7,University of Michigan, 2457 , 0.49654049654 , 1220 , 0.475376475376 , 1168 , 0.652421652422 , 1603 , 0.945054945055 , 2322 , 2396 , 0.975172975173 , 2428 , 0.988196988197 , 2276 , 0.926332926333 , 1678 , 0.682946682947
21,New York University, 1453 , 0.426015141087 , 619 , 0.138334480385 , 201 , 0.238816242257 , 347 , 0.508602890571 , 739 , 1344 , 0.924982794219 , 1453 , 1.0 , 511 , 0.351686166552 , 575 , 0.395732966277
15,Princeton University, 1106 , 0.508137432188 , 562 , 0.0696202531646 , 77 , 0.299276672694 , 331 , 0.77034358047 , 852 , 1000 , 0.904159132007 , 1062 , 0.960216998192 , 345 , 0.311934900542 , 860 , 0.777576853526
28,Georgia Institute of Technology, 1333 , 0.630157539385 , 840 , 0.271567891973 , 362 , 0.55663915979 , 742 , 0.876969242311 , 1169 , 1228 , 0.921230307577 , 1332 , 0.999249812453 , 762 , 0.571642910728 , 1150 , 0.86271567892
5,Massachusetts Institute of Technology, 1509 , 0.497680583168 , 751 , 0.360503644798 , 544 , 0.266401590457 , 402 , 0.692511597084 , 1045 , 1503 , 0.996023856859 , 1506 , 0.998011928429 , 443 , 0.293571901922 , 1005 , 0.666003976143
19,Pennsylvania State University, 3749 , 0.603627634036 , 2263 , 0.25900240064 , 971 , 0.403841024273 , 1514 , 0.821819151774 , 3081 , 3670 , 0.978927714057 , 3706 , 0.98853027474 , 2075 , 0.553480928248 , 2558 , 0.682315284076
1,Harvard University, 2091 , 0.44093735055 , 922 , 0.35581061693 , 744 , 0.343854615017 , 719 , 0.725968436155 , 1518 , 2073 , 0.991391678623 , 2025 , 0.96843615495 , 920 , 0.439980870397 , 1345 , 0.643232902917
27,Boston University, 1465 , 0.61228668942 , 897 , 0.303754266212 , 445 , 0.411604095563 , 603 , 0.774744027304 , 1135 , 1305 , 0.890784982935 , 1422 , 0.970648464164 , 812 , 0.554266211604 , 961 , 0.655972696246
24,Ohio State University, 4586 , 0.470344526821 , 2157 , 0.244003488879 , 1119 , 0.378979502835 , 1738 , 0.630614914959 , 2892 , 4138 , 0.902311382468 , 4419 , 0.963584823375 , 2302 , 0.501962494549 , 2429 , 0.529655473179
13,Duke University, 1653 , 0.496672716273 , 821 , 0.452510586812 , 748 , 0.361766485178 , 598 , 0.838475499093 , 1386 , 1627 , 0.984271022384 , 1652 , 0.999395039322 , 760 , 0.459770114943 , 1225 , 0.741076830006
16,Carnegie Mellon University, 1523 , 0.67498358503 , 1028 , 0.145764937623 , 222 , 0.521996060407 , 795 , 0.757715036113 , 1154 , 1467 , 0.963230466185 , 1468 , 0.963887065003 , 1009 , 0.662508207485 , 988 , 0.648719632305
4,University of California Berkeley, 3119 , 0.466816287272 , 1456 , 0.390509778775 , 1218 , 0.344661750561 , 1075 , 0.684514267393 , 2135 , 3050 , 0.977877524848 , 2970 , 0.952228278294 , 1212 , 0.388586085284 , 2105 , 0.674895799936
17,University of Rochester, 735 , 0.536054421769 , 394 , 0.439455782313 , 323 , 0.49387755102 , 363 , 0.915646258503 , 673 , 664 , 0.903401360544 , 735 , 1.0 , 383 , 0.521088435374 , 653 , 0.88843537415
12,Columbia University, 3278 , 0.467968273337 , 1534 , 0.366992068334 , 1203 , 0.188224527151 , 617 , 0.340756558877 , 1117 , 2975 , 0.907565588774 , 3247 , 0.990543014033 , 1015 , 0.309640024405 , 731 , 0.223001830384
22,University of Minnesota, 2948 , 0.497964721845 , 1468 , 0.0651289009498 , 192 , 0.310379918589 , 915 , 0.517299864315 , 1525 , 2662 , 0.902985074627 , 2948 , 1.0 , 1170 , 0.396879240163 , 1270 , 0.430800542741
14,University of Washington, 4694 , 0.478057094163 , 2244 , 0.169152109075 , 794 , 0.408180656157 , 1916 , 0.575202386025 , 2700 , 4225 , 0.900085215168 , 4694 , 1.0 , 2210 , 0.470813804857 , 2406 , 0.512569237324
25,University of Illinois Urbana Champaign, 1996 , 0.469438877756 , 937 , 0.113226452906 , 226 , 0.352204408818 , 703 , 0.543086172345 , 1084 , 1803 , 0.903306613226 , 1966 , 0.98496993988 , 898 , 0.449899799599 , 904 , 0.452905811623
2,University of Chicago, 2011 , 0.437095972153 , 879 , 0.39035305818 , 785 , 0.273495773247 , 550 , 0.656389855793 , 1320 , 1958 , 0.97364495276 , 2011 , 1.0 , 589 , 0.292889109896 , 1281 , 0.636996519145
29,University of Southern California, 6140 , 0.494951140065 , 3039 , 0.0201954397394 , 124 , 0.349511400651 , 2146 , 0.684690553746 , 4204 , 5576 , 0.908143322476 , 6138 , 0.999674267101 , 2454 , 0.399674267101 , 3898 , 0.634853420195
26,University of North Carolina Chapel Hill, 3163 , 0.510591210876 , 1615 , 0.419222257351 , 1326 , 0.407208346506 , 1288 , 0.83654758141 , 2646 , 2826 , 0.893455580145 , 3161 , 0.999367688903 , 1468 , 0.464116345242 , 2468 , 0.780271893772
6,Johns Hopkins University, 3657 , 0.323489198797 , 1183 , 0.499863275909 , 1828 , 0.349193327864 , 1277 , 0.707136997539 , 2586 , 2471 , 0.675690456658 , 3652 , 0.998632759092 , 1457 , 0.398414000547 , 2409 , 0.658736669401
10,University of California San Diego, 2517 , 0.475566150179 , 1197 , 0.314660309893 , 792 , 0.311879221295 , 785 , 0.565752880413 , 1424 , 2476 , 0.983710766786 , 2517 , 1.0 , 887 , 0.352403655145 , 1322 , 0.525228446563
8,Michigan State University, 2159 , 0.588698471515 , 1271 , 0.143584993052 , 310 , 0.388605836035 , 839 , 0.645206113942 , 1393 , 2006 , 0.929133858268 , 2146 , 0.99397869384 , 883 , 0.408985641501 , 1355 , 0.627605372858

In [130]:
 bines=550649
# #############  this cell is the old code


# tot_num_unique_names=0

# #list_files=['TESTING_100.Yeshiva_University.xlsx']

# master_dict_filenames={}
# for filename in list_files:
#     print filename
#     df=pandas.read_csv(path+filename, sep='|',names = ['First_Name','Last_Name','Title','Email','University','School_college','Departments','Url'])
    
#     master_dict={}
#     #First name,Last name,Title,Email,University,School/college,Department(s),url
#     list_for_dropping=[]
#     cont =0

#     for index, row in df.iterrows():
#         cont +=1
#         #print index, row['Last_Name'], row['First_Name']
#         try:
#             name= str(row['First_Name']) + ' ' +str(row['Last_Name'])
#             #print name
#             if name not in master_dict:
#                 master_dict [name] ={}
#                 tot_num_unique_names +=1
#             else:
#                 list_for_dropping.append(index)                    
#         except TypeError:
#                 pass
#     print "before dropping",len(df.values)    
#     print  " # rows to be dropped: ", len(list_for_dropping)  , "  out of:",cont 
    
    
#     ######## i create a new dataframe that excludes some rows (the duplicates)
#     df2= df.drop(df.index[list_for_dropping])      #(if i only drop, df doesnt actually get modify)
    
#     print "after dropping", len(df2.values)
#     new_file_name=path+filename.split(".xlsx")[0]+"_removed_duplicates.xlsx"
#     df2.to_csv(new_file_name, sep='|', header=False, index=False)
#     print "written:", new_file_name
    
    
#     print "tot num. unique names",tot_num_unique_names,"\n\n\n"
    
#     df2=df[df.index not in list_for_dropping]

3280

In [81]:
 bines=550649# import pandas
# path='/home/juliaponcela/at_NICO/Dropbox_collaboration_patterns/Data/Vinu_University_Sheets/100_universities_aux/'
# list_files_top30=['20.Harvard_University_removed_duplicates.xlsx',\
#  '63.University_of_Chicago_removed_duplicates.xlsx',\
#  '41.Stanford_University_removed_duplicates.xlsx',\
#  '53.University_of_California_Berkeley_removed_duplicates.xlsx',\
#  '25.Massachusetts_Institute_of_Technology_removed_duplicates.xlsx', \
#  '23.Johns_Hopkins_University_removed_duplicates.xlsx',\
#  '79.University_of_Michigan_removed_duplicates.xlsx',\
#  '26.Michigan_State_University_removed_duplicates.xlsx',\
#  '99.Yale_University_removed_duplicates.xlsx',\
#  '58.University_of_California_San_Diego_removed_duplicates.xlsx',\
#  '56.University_of_California_Los_Angeles_removed_duplicates.xlsx', \
#  '10.Columbia_University_removed_duplicates.xlsx', \
#  '14.Duke_University_removed_duplicates.xlsx', \
#  '94.University_of_Washington_removed_duplicates.xlsx', \
#  '35.Princeton_University_removed_duplicates.xlsx', \
#  '6.Carnegie_Mellon_University_removed_duplicates.xlsx', \
#  '88.University_of_Rochester_removed_duplicates.xlsx', \
#  '1.Arizona_State_University_removed_duplicates.xlsx', \
#  '34.Pennsylvania_State_University_removed_duplicates.xlsx', \
#  '11.Cornell_University_removed_duplicates.xlsx', \
#  '27.New_York_University_removed_duplicates.xlsx', \
#  '80.University_of_Minnesota_removed_duplicates.xlsx', \
#  '44.Temple_University_removed_duplicates.xlsx', \
#  '31.Ohio_State_University_removed_duplicates.xlsx', \
#  '73.University_of_Illinois_Urbana_Champaign_removed_duplicates.xlsx', \
#  '84.University_of_North_Carolina_Chapel_Hill_removed_duplicates.xlsx', \
#  '3.Boston_University_removed_duplicates.xlsx', \
#  '19.Georgia_Institute_of_Technology_removed_duplicates.xlsx', \
#  '90.University_of_Southern_California_removed_duplicates.xlsx', \
#  '30.Northwestern_University_removed_duplicates.xlsx']
# tot_num_unique_names=0
# dict_dept_number_people={}
# for filename in list_files_top30:
#     print filename
#     df=pandas.read_csv(path+filename, sep='|',names = ['First_Name','Last_Name','Title','Email','University','School_college','Departments','Url'])
    
#     master_dict={}
#     #First name,Last name,Title,Email,University,School/college,Department(s),url
#     list_for_dropping=[]
#     cont =0
    
#     for index, row in df.iterrows():
            
#             dept=""
#             cont +=1
        
#             name= str(row['First_Name']) + ' ' +str(row['Last_Name'])
#             dept=str(row['Departments']).title()
          
            
#             ###### I group departments by similarity
            
#             if "Art" in dept:
#                 dept ="Art"
            
#             elif "African" in dept:
#                 dept ="African Studies"                   
          
#             elif "Accounting" in dept:
#                  dept ="Accounting"
#             elif "Anthropology" in dept:
#                 dept ="Anthropology"
         
#             elif "Agricultural" in dept:
#                 dept ="Agriculture"
#             elif "Asian" in dept:
#                 dept ="Asian Studies"
                
#             elif "Biochemistry" in dept  or "Biophysics" in dept or "Biomedical" in dept or "Biology" in dept  or  "Molecular" in dept:
#                  dept ="Biological"
            
            

#             elif "Business" in dept:
#                   dept ="Business"

#             elif "Cancer" in dept:
#                 dept ="Cancer"

#             elif "Chemical" in dept:
#                 dept ="Chemical"
#             elif "Classics" in dept or "Latin" in dept:
#                 dept ="Classics"

#             elif "Communication" in dept:
#                 dept ="Communication"

#             elif "Comparative" in dept:
#                 dept ="Comparative Studies"

#             elif "Computer" in dept:
#                 dept ="Computer Science"

#             elif "Earth" in dept  or "Ecology" in dept:
#                 dept ="Earth Sciences and Ecology"

#             elif "Economics" in dept:
#                 dept ="Economics"

#             elif "Education" in dept:
#                 dept ="Education"
#             elif "Electrical" in dept:
#                  dept ="Electrical Engineering"

#             elif "English" in dept:
#                 dept ="English"

#             elif "Environmental" in dept:
#                 dept ="Environmental Sciences"
#             elif "Film" in dept:
#                 dept ="Film Studies"
#             elif "Food" in dept:
#                         dept ="Food"
#             elif "French" in dept  or    "Language" in dept   or  "German" in dept or    "Russian" in dept\
#             or "Romance" in dept   or  "Russian" in dept or "Slavic" in dept  or "Scandinavian" in dept\
#             or "Spanish" in dept   or     "Linguistics"  in dept   or     "Letters"  in dept   or "Languag" in dept:
#                 dept ="Languages"

#             elif "Mechanical" in dept :                                                      
#                  dept ="Mechanical"

#             elif "Health" in dept:
#                 dept ="Health"

#             elif "History" in dept:
#                 dept ="History"

#             elif "Immuno" in dept or "Epidemiology" in dept or "Microbiology" in dept :
#                 dept ="Immunology or Epidemiology or Microbiology"
                
#             elif "Industrial" in dept:
#                 dept ="Industrial"

#             elif "Information" in dept:
#                 dept ="Information"

#             elif "Law" in dept or "Legal" in dept :
#                 dept ="Law"

#             elif "Management" in dept  or "Marketing" in dept :
#                 dept ="Management or Marketing"

#             elif "Materials" in dept:
#                 dept ="Materials"

#             elif "Mathematics" in dept:
#                 dept ="Mathematics"

#             elif "Middle East" in dept  or  "Near Eastern" in dept  :
#                 dept ="Middle Eastern"
                
#             elif "Music" in dept:
#                 dept ="Music"

#             elif "Neuro" in dept or "Neuroscience" in dept  or "Obstetrics" in dept\
#             or "Ophthalmology" in dept       or "Orthopaedic" in dept  or "Otolaryngology" in dept\
#             or "Pediatric" in dept or "Pulmonary" in dept or "Radiation" in dept or "Radiology" in dept\
#             or "Anesthesia" in dept or "Cardi" in dept or "Dermatology" in dept or "Hematology" in dept\
#              or "Surg" in dept or "Transplan" in dept or "Urolo" in dept or "Vascul" in dept\
#             or "Nursing" in dept or "Nutr" in dept or "Optics" in dept or "Ortho" in dept or "Physiol" in dept\
#             or "Rehabilitation" in dept  or "Rheumatology" in dept or "Respiratory" in dept   or "Medic" in dept:
#                  dept ="Medicine"

                    
                    
                    
                    

#             elif "Pharmacology" in dept or "Pharmacy" in dept or "Pharmaceut" in dept :
#                 dept ="Pharmacology"

#             elif "Physics" in dept:
#                 dept ="Physics"
                
#             elif "Political" in dept:
#                 dept ="Political Science"
                
#             elif "Psychiatry" in dept  or "Psycho" in dept:
#                 dept ="Psychiatry or Psychology"

#             elif "Public" in dept:
#                 dept ="Public Affairs and Health"
                
#             elif "Risk" in dept:
#                 dept ="Risk"
                
#             elif "Social" in dept or "Socio" in dept :
#                 dept ="Social or Sociology"  
                
          
#             elif "Statistics" in dept:
#                 dept ="Statistics"
                
#             elif "Theater" in dept:
#                 dept ="Theater"
                
#             elif "Urban" in dept:
#                 dept ="Urban"
                
#             elif "Veterinary" in dept:
#                 dept ="Veterinary"
                
#             elif "Visual" in dept:
#                 dept ="Visual Arts"
                
#             elif "Women" in dept:
#                 dept ="Women's Studies"
                
#             elif "Writing" in dept:
#                 dept ="Writing"
#             #else :
#              #   dept="Other"

#             #print " ---->",dept
#             #raw_input()
          
            
            
            
            
#             if dept not in dict_dept_number_people:
#                 dict_dept_number_people[dept]=1.                
#             else:
#                  dict_dept_number_people[dept] +=1.  
                
#             if name not in master_dict:
#                 master_dict [name] ={}
#                 tot_num_unique_names +=1
#             else:
#                 list_for_dropping.append(index)     
                
                
                
                
#         #except TypeError:
#          #       pass
#     print "before dropping",len(df.values)    
#     print  " # rows to be dropped: ", len(list_for_dropping)  , "  out of:",cont 
    
#     #cont=0
#     #for item in df.Departments:
#      #   print item
#       #  if cont == 10:
#        #     break
#         #cont +=1
    
#     #raw_input()
    
#     ######## i create a new dataframe that excludes some rows (the duplicates)
#     #df2= df.drop(df.index[list_for_dropping])      #(if i only drop, df doesnt actually get modify)
    
#     #print "after dropping", len(df2.values)
#     #new_file_name=path+filename.split(".xlsx")[0]+"_removed_duplicates.xlsx"
#     #df2.to_csv(new_file_name, sep='|', header=False, index=False)
#     #print "written:", new_file_name
    
    
#     print "tot num. unique names",tot_num_unique_names,"\n\n\n"
    
    
    
# tot_cont=0    
# for dept in sorted(dict_dept_number_people):
#     if dict_dept_number_people[dept] >100:
#         print dept, ";",dict_dept_number_people[dept]
#         tot_cont += dict_dept_number_people[dept]
        
        
        
# print "\n\n# people in big categories:",tot_cont